<?php

/**
 * Visit type reference list (CNAM "Types de Missions" register).
 * Bilingual FR/AR labels. Codes are stable identifiers — safe to store in the
 * database and reference in code; only the fr/ar labels should ever change.
 *
 * To add/edit a type: just edit this array. No migration needed since
 * visites.type_visite is a plain string column validated against this list.
 */

return [
        'diagnostic' => ['fr' => 'Diagnostic', 'ar' => 'معاينة'],
        'at_mortel' => ['fr' => 'AT Mortel', 'ar' => 'حادث قاتل'],
        'maladie_professionnelle' => ['fr' => 'Maladie professionnelle', 'ar' => 'مرض مهني'],
        'bonus' => ['fr' => 'Bonus', 'ar' => 'تخفيض'],
        'at_grave' => ['fr' => 'AT Grave', 'ar' => 'حادث خطير'],
        'diagnostic_2' => ['fr' => 'Diagnostic', 'ar' => 'تفقد'],
        'campagne' => ['fr' => 'Campagne', 'ar' => 'حملة'],
        'assistance_complement' => ['fr' => 'Assistance Complément', 'ar' => 'مساعدة قرض'],
        'suite' => ['fr' => 'Suite', 'ar' => 'تتمة'],
        'assistance' => ['fr' => 'Assistance', 'ar' => 'مساعدة'],
        'majoration_du_taux_de_cotisation' => ['fr' => 'Majoration du taux de cotisation', 'ar' => 'الترفيع في نسبة المساهمة'],
        'activite' => ['fr' => 'Activité', 'ar' => 'نشاط'],
        'pret_sst' => ['fr' => 'Prêt SST', 'ar' => 'قرض'],
        'comite_sst' => ['fr' => 'Comité SST', 'ar' => 'لجنة صحة و سلامة'],
        'lieu_mp' => ['fr' => 'Lieu MP', 'ar' => 'مكان المرض'],
        'lieu_am' => ['fr' => 'Lieu AM', 'ar' => 'مكان حادث قاتل'],
        'suite_maladie_professionnelle' => ['fr' => 'Suite (maladie professionnelle)', 'ar' => 'تتمّة (مرض مهني)'],
        'lieu_at' => ['fr' => 'Lieu AT', 'ar' => 'مكان الحادث'],
        'assistance_bonus' => ['fr' => 'Assistance Bonus', 'ar' => 'مساعدة تخفيض'],
        'bilan_social' => ['fr' => 'Bilan social', 'ar' => 'رصيد إجتماعي'],
        'at' => ['fr' => 'AT', 'ar' => 'حادث شغل'],
        'at_collectif' => ['fr' => 'AT Collectif', 'ar' => 'حادث شغل خطير جماعي'],
        'suite_pret_sst' => ['fr' => 'Suite prêt SST', 'ar' => 'تتمّة قرض'],
        'am_collectif' => ['fr' => 'AM Collectif', 'ar' => 'حادث قاتل جماعي'],
        'suite_at_mortel' => ['fr' => 'Suite AT mortel', 'ar' => 'تتمة حادث قاتل'],
        'suite_maladie_professionnelle_2' => ['fr' => 'Suite maladie professionnelle', 'ar' => 'تتمة مرض مهني'],
        'suite_maladie_professionnelle_3' => ['fr' => 'Suite maladie professionnelle', 'ar' => 'تتمّة مرض مهني'],
        'comite_maladie_professionnelle' => ['fr' => 'Comité maladie professionnelle', 'ar' => 'لجنة م مهني'],
        'comite_national' => ['fr' => 'Comité national', 'ar' => 'اللجنة الوطنية'],
        'proces_verbal_denquete' => ['fr' => 'Procès-verbal d’enquête', 'ar' => 'محضر بحث'],
        'seance_de_sensibilisation' => ['fr' => 'Séance de sensibilisation', 'ar' => 'حلقة تحسيسية'],
        'at_collectif_2' => ['fr' => 'AT Collectif', 'ar' => 'حادث شغل جماعي'],
        'mp_mortel' => ['fr' => 'MP Mortel', 'ar' => 'مرض مهني قاتل'],
        'suivi_des_tests_1' => ['fr' => 'Suivi des tests 1', 'ar' => 'متابعة الإختبارات 1'],
        'suivi_des_tests_3' => ['fr' => 'Suivi des tests 3', 'ar' => 'متابعة الإختبارات 3'],
        'assistance_pret_bonus' => ['fr' => 'Assistance prêt + bonus', 'ar' => 'مساعدة قرض + تخفيض'],
        'lieu_mp_2' => ['fr' => 'Lieu MP', 'ar' => 'مكان مرض مهني'],
        'maladie_professionnelle_1' => ['fr' => 'Maladie professionnelle 1', 'ar' => 'مرض مهني 1'],
        'accidents_repetitifs' => ['fr' => 'Accidents répétitifs', 'ar' => 'حوادث متكرّرة'],
        'suivi_pret_sst' => ['fr' => 'Suivi prêt SST', 'ar' => 'متابعة قرض'],
        'at_trajet' => ['fr' => 'AT Trajet', 'ar' => 'حادث شغل مسير'],
        'at_trajet_2' => ['fr' => 'AT Trajet', 'ar' => 'حادث طريق'],
        'at_grave_trajet' => ['fr' => 'AT Grave Trajet', 'ar' => 'حادث خطير مسير'],
        'at_collectif_3' => ['fr' => 'AT Collectif', 'ar' => 'حادث جماعي'],
        'suite_pret_sst_2' => ['fr' => 'Suite prêt SST', 'ar' => 'تتمة قرض'],
        'lieu_at_mortel' => ['fr' => 'Lieu AT mortel', 'ar' => 'مكان  حادث قاتل'],
        'assistance_pret_bonus_2' => ['fr' => 'Assistance prêt + bonus', 'ar' => 'مساعدة قرض+تخفيض'],
        'assistance_bonus_pret' => ['fr' => 'Assistance bonus/prêt', 'ar' => 'مساعدة تخفيض/قرض'],
        'at_grave_2' => ['fr' => 'AT Grave', 'ar' => 'حادث شغل خطير'],
        'assistance_bonus_pret_2' => ['fr' => 'Assistance bonus-prêt', 'ar' => 'مساعدة تخفيض-قرض'],
        'at_trajet_3' => ['fr' => 'AT Trajet', 'ar' => 'حادث مسير'],
        'at_mortel_trajet' => ['fr' => 'AT Mortel Trajet', 'ar' => 'حادث مسير قاتل'],
        'diagnostic_assistance' => ['fr' => 'Diagnostic - Assistance', 'ar' => 'معاينة - مساعدة'],
        'comite_maladie_professionnelle_2' => ['fr' => 'Comité maladie professionnelle', 'ar' => 'لجنة مرض مهني'],
        'diagnostic_protection_civile' => ['fr' => 'Diagnostic Protection civile', 'ar' => 'معاينة الحماية المدنية'],
        'at_auto' => ['fr' => 'AT Auto', 'ar' => 'تصريح ذاتي'],
        'assistance_pret_sst' => ['fr' => 'Assistance prêt SST', 'ar' => 'مساعدة قرض'],
        'mp_auto' => ['fr' => 'MP Auto', 'ar' => 'مكان حادث خطير'],
        'at_auto_2' => ['fr' => 'AT Auto', 'ar' => 'محضر بحث حادث مسير'],
        'pv_at_trajet' => ['fr' => 'PV AT Trajet', 'ar' => 'محضر بحث حادث شغل'],
        'pv_enquete_at_grave' => ['fr' => 'PV enquête AT grave', 'ar' => 'محضر بحث حادث خطير'],
        'pv_enquete_at_collectif' => ['fr' => 'PV enquête AT collectif', 'ar' => 'محضر بحث حادث شغل جماعي'],
        'assistance_web' => ['fr' => 'Assistance Web', 'ar' => 'مساعدة موقع واب'],
        'declaration_procede' => ['fr' => 'Déclaration Procédé', 'ar' => 'تصريح أساليب'],
        'comite' => ['fr' => 'Comité', 'ar' => 'لجنة'],
        'at_collectif_grave' => ['fr' => 'AT Collectif Grave', 'ar' => 'حادث جماعي خطير'],
        'declaration_des_methodes_de_travail' => ['fr' => 'Déclaration des méthodes de travail', 'ar' => 'تصريح أساليب العمل'],
        'declaration_at' => ['fr' => 'Déclaration AT', 'ar' => 'تصريح ذاتي حادث شغل'],
        'declaration_mp' => ['fr' => 'Déclaration MP', 'ar' => 'تصريح ذاتي مرض مهني'],
        'suivi_2025' => ['fr' => 'Suivi 2025', 'ar' => 'متابعة 2025'],
];